### ISSUE TITLE
Can this implementation replicate the result in the original paper?

### ISSUE THREAD

**Issue by agoodweathercc** [benedekrozemberczki/GraphWaveMachine#1]
Hello,

Can this implementation replicate the result in the original paper? How about the speed?

Thank you!

**Comment by benedekrozemberczki** [comment]
It is faster. This implementation has an O(|V|^2) runtime while the one by Donnat has a runtime of O(|V|^3) runtime. Memory complexity is the same. Interestingly, in the original implementation they did not use the approximation. I tried out them on multiple problems. There is no predictive performance difference.

**Comment by agoodweathercc** [comment]
Thanks a lot for a quick reply!

**Comment by benedekrozemberczki** [comment]
Sidenote for complexity: they say in the paper that the runtime is O(|E|) with the approximation. However, as the approximation order (Laplacian power order) converges to the graph diameter (which is small in most complex networks) the runtime complexity becomes quadratic.

**Comment by agoodweathercc** [comment]
I am going to use the embedding mainly for node classification and link prediction. On the original paper, it seems that the when the number of nodes is 10^5, the running time is 10^4, which seems to quite slow. Did you try it on large network dataset such as Flickr/youtube and how long it takes?

**Comment by benedekrozemberczki** [comment]
Yes I did. It takes a day on 60,000 nodes and a lot of memory.
