### ISSUE TITLE
The whole embedding output be the same

### ISSUE THREAD

**Issue by Clearloveyuan** [benedekrozemberczki/GraphWaveMachine#2]
why use my data to text ,the whole node embedding  output the same result?

**Comment by benedekrozemberczki** [comment]
That sounds problematic. Can You drop me your dataset?

**Comment by Clearloveyuan** [comment]
> That sounds problematic. Can You drop me your dataset?

Thans so much. I sent you my data.

**Comment by benedekrozemberczki** [comment]
The rows are not in the right format. For this procedure rows should be comma separated.

**Comment by Clearloveyuan** [comment]
> The rows are not in the right format. For this procedure rows should be comma separated.

I am sorry to send you the original data . I make the data in a right way. The problem also exists.I send you my new data .Thanks so much !

**Comment by benedekrozemberczki** [comment]
It works for me perfectly.

What is your heat wave coefficient? What is the dataset about?
