### ISSUE TITLE
a small problem about parser. 

### ISSUE THREAD

**Issue by WMF1997** [benedekrozemberczki/GraphWaveMachine#5]
hello @benedekrozemberczki 
when i run the code with ```python src/main.py``` for a try. it tells me that module parser do not have parameter_parser. 
I am now using python 3.7.3. As far as I know, Python3 itself has the module with the name ```parser```. I changed the file name of ```parser.py``` to some other names, and then it works. Hope to change the name. 

this is a screenshot (sorry, this is another repo's)

![image](https://user-images.githubusercontent.com/37621591/65399160-b37fde00-dded-11e9-9038-c9bf3721086f.png)

and this is the description of that. 

![image](https://user-images.githubusercontent.com/37621591/65399204-df02c880-dded-11e9-8e50-1917e080b535.png)

change the name of the file, and then it works. (no GPU version is running...)

? I guess that you are using Python 2.7, instead of Python 3. (sorry, i am now using Microsoft Windows for example, I remembered that when I use Ubuntu to run the same code several months ago, I have met the same problem... (I also use Python 3 in Ubuntu) 
And I hope ALL THE ```parser``` names can be changed. 

yours sincerely, 
@wmf1997.

**Comment by benedekrozemberczki** [comment]
Thank You. It is troublesome as I do not plan to move to that version of
python (mainly TensorFlow and Torch issues).

**Comment by WMF1997** [comment]
got that, thank you~

**Comment by benedekrozemberczki** [comment]
I will consider changing all of the parser functions in the paper implementations.
