### ISSUE TITLE
Graphwave Installation

### ISSUE THREAD

**Issue by fidelle** [benedekrozemberczki/GraphWaveMachine#8]
Hi how do I install the package. I was not able to install it via pip. I tried cloning the repo into a folder but when I import graphwave it is having issues importing.

**Comment by benedekrozemberczki** [comment]
Use the KarateClub library, please star the repo if you end up using the
library.

**Comment by fidelle** [comment]
I used KarateClub at first. But wanted to make some modifications to the heat diffusion function in graphwave.py using pygsp instead.It seems I am limited with the KarateClub function.

**Comment by benedekrozemberczki** [comment]
The GraphWave library cannot be installed. However, you can take the class
and modify it. If you want to you can open a PR for Karate Club.

**Comment by fidelle** [comment]
Ok thank you.
